---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  - EMBER_TRY_SCENARIO=ember-2.18.X
  - EMBER_TRY_SCENARIO=ember-3.1.X
  - EMBER_TRY_SCENARIO=ember-beta

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn lint:js
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

deploy:
  provider: npm
  email: admin@ember-redux.com
  skip_cleanup: true
  api_key:
    secure: EFpURL2HfyeDKEed2Mj4i4dQZOEPE7BUNUXBXOYU3nkkHtNRCsW3zsJg2gFHAslMZjjMtXrwHmn+T2ZQpQKqFHHx60cljvKvaErhQq7TjdZPIuB7+rXMUX/Zq+hX9apQ7v4NClDI9KPAC7En28zcP/FMnmNlADLUww6MkelN7GUx3z6CwSNe7cPAhPh/ZV5PYjYI6Pl4RuAb5JMW2kqHDgUK8pI5mhpzAfZC1daaxfZ6yyTHrI3WyPx1amEmNMded5XpP0Bk3fRvK0QNnacPzS06YFREjoqnThtPUrGx75vja47wMeobp/ToXFn/6cRaG35X7EUUegXUX4Cg9omFixxPef4/Z30B74xHRkw9IaJf9kDvylqKz4+MfsZvw/w/LZJwuGOX0CWmbTyoDZ/ychPk+38FyNmd2vXUbI4Ttw9xk5vq8vb86OWygQTKR28Bk3V9sfiy5rwmiPEaDacFoQk8Xn3OM49PgbJSjFYlVLjqdfhk8K9X05QvZllGOOSqImlUCNn0snzMMAX5X0EMd1LoFuEBARKgJKQ8AvO02/hLkbJ7ao4aEP4OemPuWxt4PUes/AKwiYcOWCnKUv5Pyt8D31dOwgsAdZHh41n6QQUzc4SMuXFcrrTysTsWtWsyeT+rEPAz4jRQF0B7FMauZEl7G1SlOGhctJg9vXfkSbU=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'default'"
    node: 'stable'
    tags: true
